package com.fittrack.auth;
import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.security.crypto.password.PasswordEncoder; import java.security.*; import java.nio.charset.StandardCharsets; import java.time.*; import java.util.*; import org.springframework.beans.factory.annotation.Value;
@Service public class AuthService {
 UserRepository users; RefreshTokenRepository tokens; PasswordEncoder encoder; JwtService jwt; Duration ttl;
 public AuthService(UserRepository u,RefreshTokenRepository t,PasswordEncoder p,JwtService j,@Value("${app.refresh-ttl}") Duration d){users=u;tokens=t;encoder=p;jwt=j;ttl=d;}
 @Transactional public Tokens register(Credentials c){validate(c);String email=c.email().toLowerCase();if(users.existsByEmail(email))throw new IllegalArgumentException("Email already registered");User u=new User();u.setEmail(email);u.setPasswordHash(encoder.encode(c.password()));users.save(u);return issue(u);}
 public Tokens login(Credentials c){validate(c);User u=users.findByEmail(c.email().toLowerCase()).orElseThrow(()->new IllegalArgumentException("Invalid credentials"));if(!encoder.matches(c.password(),u.getPasswordHash()))throw new IllegalArgumentException("Invalid credentials");return issue(u);}
 @Transactional(noRollbackFor=IllegalArgumentException.class) public Tokens rotate(String raw){RefreshToken old=find(raw).orElseThrow(()->new IllegalArgumentException("Invalid refresh token"));if(old.isUsed()||old.isRevoked()){revokeFamily(old.getFamilyId());throw new IllegalArgumentException("Refresh token reuse detected");}if(!old.getExpiresAt().isAfter(Instant.now())){old.setRevoked(true);tokens.save(old);throw new IllegalArgumentException("Invalid refresh token");}User u=users.findById(old.getUserId()).orElseThrow();String rawNew=secret();RefreshToken replacement=new RefreshToken();replacement.setUserId(old.getUserId());replacement.setFamilyId(old.getFamilyId());replacement.setTokenHash(hash(rawNew));replacement.setExpiresAt(Instant.now().plus(ttl));old.setUsed(true);old.setRevoked(true);old.setReplacedByHash(replacement.getTokenHash());tokens.save(old);tokens.save(replacement);return new Tokens(jwt.access(u),rawNew,replacement.getExpiresAt(),safeUser(u));}
 @Transactional public void logout(String raw){if(raw==null||raw.isBlank())return;find(raw).ifPresent(t->{t.setRevoked(true);tokens.save(t);});}
 public java.util.Map<String,Object> me(String id){User u=users.findById(java.util.UUID.fromString(id)).orElseThrow();return java.util.Map.of("id",u.getId(),"email",u.getEmail(),"enabled",u.isEnabled());}
 private Optional<RefreshToken> find(String raw){return raw==null||raw.isBlank()?Optional.empty():tokens.findByTokenHash(hash(raw));} private void revokeFamily(UUID id){tokens.findAllByFamilyId(id).forEach(t->{t.setRevoked(true);tokens.save(t);});} private void validate(Credentials c){if(c==null||c.email()==null||c.email().isBlank()||c.password()==null||c.password().length()<8)throw new IllegalArgumentException("Valid email and password are required");}
 private Tokens issue(User u){String r=secret();RefreshToken t=new RefreshToken();t.setUserId(u.getId());t.setTokenHash(hash(r));t.setExpiresAt(Instant.now().plus(ttl));tokens.save(t);return new Tokens(jwt.access(u),r,t.getExpiresAt(),safeUser(u));} private Map<String,Object> safeUser(User u){return Map.of("id",u.getId(),"email",u.getEmail(),"enabled",u.isEnabled());} private static String secret(){return UUID.randomUUID().toString()+UUID.randomUUID();} static String hash(String v){return java.util.HexFormat.of().formatHex(sha(v));} private static byte[] sha(String v){try{return MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8));}catch(Exception e){throw new IllegalStateException(e);}}
}
