// @vitest-environment jsdom
/**
 * Phase 9 Coach surface, through the real component and the real API client.
 *
 * <p>Pins the contract regression that motivated the rewrite: the view used to read a
 * `payload.review` shape the backend never sent, so it could fail even with a working provider. The
 * assertions here are deliberately about what reaches the user: a structured contract, a labelled
 * fallback that is never passed off as AI output, and distinct messages per failure status.
 */
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import CoachView from "../src/views/CoachView";
import { buildLocalFallback, windowLabel } from "../src/lib/coachFallback";
import { setAuthTokens } from "../src/lib/api/apiClient";
import { ALLOWED_WINDOW_DAYS, DEFAULT_WINDOW_DAYS, MAX_QUESTION_LENGTH } from "../src/lib/api/coachApi";

type Call = { url: string; method: string; body: any; headers: Record<string, string> };
let calls: Call[] = [];

function stubFetch(status: number, body: unknown = {}) {
  vi.spyOn(globalThis, "fetch").mockImplementation(async (input: RequestInfo | URL, init?: RequestInit) => {
    const headers: Record<string, string> = {};
    new Headers(init?.headers).forEach((v, k) => { headers[k.toLowerCase()] = v; });
    calls.push({
      url: String(input),
      method: init?.method ?? "GET",
      body: init?.body ? JSON.parse(String(init.body)) : undefined,
      headers,
    });
    return { ok: status >= 200 && status < 300, status, json: async () => body } as Response;
  });
}

const VALID = {
  summary: "A steady week with good consistency.",
  observations: ["Three completed sessions.", "Protein averaged above target."],
  recommendations: ["Keep the current weekly rhythm."],
  next_actions: ["Schedule next week's first session."],
  warnings: ["Recovery trended down midweek."],
  model: "gpt-4o-mini",
  request_id: "req-123",
};

const fallbackInput = { sessions: 3, totalMinutes: 180, avgSleepHours: 7.1, mealsLogged: 14, habitsTracked: 4 };

function ask() {
  fireEvent.click(screen.getByRole("button", { name: /get insights/i }));
}

beforeEach(() => {
  calls = [];
  setAuthTokens("test-access-token");
});

afterEach(() => {
  cleanup();
  vi.restoreAllMocks();
});

describe("CoachView", () => {
  it("renders the structured contract from the server", async () => {
    stubFetch(200, VALID);
    render(<CoachView fallbackInput={fallbackInput} />);
    ask();

    await waitFor(() => expect(screen.getByText(VALID.summary)).toBeTruthy());
    expect(screen.getByText("Three completed sessions.")).toBeTruthy();
    expect(screen.getByText("Keep the current weekly rhythm.")).toBeTruthy();
    expect(screen.getByText("Schedule next week's first session.")).toBeTruthy();
    expect(screen.getByText("Recovery trended down midweek.")).toBeTruthy();
    expect(screen.getByText(/Generated by gpt-4o-mini/)).toBeTruthy();
  });

  it("posts to /coach/insights with the default 7 day window", async () => {
    stubFetch(200, VALID);
    render(<CoachView fallbackInput={fallbackInput} />);
    ask();

    await waitFor(() => expect(calls).toHaveLength(1));
    expect(calls[0].url).toContain("/coach/insights");
    expect(calls[0].body).toEqual({ window_days: DEFAULT_WINDOW_DAYS });
  });

  it("sends only the allowed windows", async () => {
    stubFetch(200, VALID);
    render(<CoachView fallbackInput={fallbackInput} />);

    for (const days of ALLOWED_WINDOW_DAYS) {
      fireEvent.click(screen.getByRole("button", { name: `${days}d` }));
    }
    ask();

    await waitFor(() => expect(calls).toHaveLength(1));
    expect(calls[0].body.window_days).toBe(90);
  });

  it("sends the question when one is typed", async () => {
    stubFetch(200, VALID);
    render(<CoachView fallbackInput={fallbackInput} />);
    fireEvent.change(screen.getByLabelText(/ask a question/i), { target: { value: "Should I deload?" } });
    ask();

    await waitFor(() => expect(calls).toHaveLength(1));
    expect(calls[0].body.question).toBe("Should I deload?");
  });

  it("omits the question key entirely when none is asked", async () => {
    stubFetch(200, VALID);
    render(<CoachView fallbackInput={fallbackInput} />);
    ask();

    await waitFor(() => expect(calls).toHaveLength(1));
    expect(Object.keys(calls[0].body)).not.toContain("question");
  });

  it("caps the question at the server limit and refuses to send a longer one", async () => {
    stubFetch(200, VALID);
    render(<CoachView fallbackInput={fallbackInput} />);
    const field = screen.getByLabelText(/ask a question/i) as HTMLTextAreaElement;

    expect(field.maxLength).toBe(MAX_QUESTION_LENGTH);
    // A value past the cap cannot survive the attribute, so a client bypass is what matters here.
    fireEvent.change(field, { target: { value: "a".repeat(MAX_QUESTION_LENGTH + 1) } });
    ask();

    await waitFor(() => expect(calls).toHaveLength(0));
    expect(screen.getByRole("alert").textContent).toMatch(/under 500 characters/i);
  });


  it("sends an idempotency key so a replay cannot be billed twice", async () => {
    stubFetch(200, VALID);
    render(<CoachView fallbackInput={fallbackInput} />);
    ask();

    await waitFor(() => expect(calls).toHaveLength(1));
    expect(calls[0].headers["idempotency-key"]).toBeTruthy();
  });

  it("keeps one key across a retry of the same question", async () => {
    stubFetch(409, { code: "coach_request_already_processed", error: "Conflict" });
    render(<CoachView fallbackInput={fallbackInput} />);
    ask();
    await waitFor(() => expect(screen.getByRole("alert")).toBeTruthy());
    const firstKey = calls[0].headers["idempotency-key"];

    stubFetch(200, VALID);
    ask();
    await waitFor(() => expect(calls).toHaveLength(2));
    expect(calls[1].headers["idempotency-key"]).toBe(firstKey);
  });

  it("mints a new key when the user clears the form for a new question", async () => {
    stubFetch(200, VALID);
    render(<CoachView fallbackInput={fallbackInput} />);
    ask();
    await waitFor(() => expect(calls).toHaveLength(1));
    const firstKey = calls[0].headers["idempotency-key"];

    fireEvent.click(screen.getByRole("button", { name: /clear/i }));
    ask();
    await waitFor(() => expect(calls).toHaveLength(2));
    expect(calls[1].headers["idempotency-key"]).not.toBe(firstKey);
  });

  it("shows a quota message on 429 and does not substitute a fallback", async () => {
    stubFetch(429, { error: "Too Many Requests" });
    render(<CoachView fallbackInput={fallbackInput} />);
    ask();

    await waitFor(() => expect(screen.getByRole("alert").textContent).toMatch(/request limit/i));
    expect(screen.queryByText(/not AI advice/i)).toBeNull();
  });

  it("explains a 409 replay rather than showing a generic failure", async () => {
    stubFetch(409, { code: "coach_request_already_processed", error: "Conflict" });
    render(<CoachView fallbackInput={fallbackInput} />);
    ask();

    await waitFor(() => expect(screen.getByRole("alert").textContent).toMatch(/already processed/i));
  });

  it("falls back to a labelled local summary when the provider is unavailable", async () => {
    stubFetch(502, { error: "Bad Gateway" });
    render(<CoachView fallbackInput={fallbackInput} />);
    ask();

    await waitFor(() => expect(screen.getByText(/not AI advice/i)).toBeTruthy());
    // The fallback must describe the user's own records and must not claim a model produced it.
    expect(screen.getByText(/your own recorded numbers/i)).toBeTruthy();
    expect(screen.queryByText(/Generated by/)).toBeNull();
  });

  it("always states the general-wellness boundary", () => {
    stubFetch(200, VALID);
    render(<CoachView fallbackInput={fallbackInput} />);

    const text = document.body.textContent ?? "";
    expect(text).toMatch(/does not diagnose/i);
    expect(text).toMatch(/emergency service/i);
  });

  it("survives a response whose optional arrays are missing", async () => {
    // The server validates, but a dropped field must not crash the renderer.
    stubFetch(200, { summary: "Only a summary.", model: "m", request_id: "r" });
    render(<CoachView fallbackInput={fallbackInput} />);
    ask();

    await waitFor(() => expect(screen.getByText("Only a summary.")).toBeTruthy());
    expect(screen.getByRole("button", { name: /get insights/i })).toBeTruthy();
  });
});

describe("buildLocalFallback", () => {
  it("is deterministic for identical input", () => {
    expect(buildLocalFallback(fallbackInput, 7)).toEqual(buildLocalFallback(fallbackInput, 7));
  });

  it("never claims a model produced it", () => {
    expect(buildLocalFallback(fallbackInput, 7).model).toBe("");
  });

  it("says so plainly when there is no data at all", () => {
    const result = buildLocalFallback({}, 7);
    expect(result.summary).toMatch(/not enough recorded data/i);
    expect(result.observations).toHaveLength(0);
  });

  it("describes a single session without pluralising it", () => {
    const result = buildLocalFallback({ sessions: 1, totalMinutes: 45 }, 7);
    expect(result.observations.join(" ")).toMatch(/completed 1 workout across/);
  });

  it("flags a thin window rather than inventing encouragement", () => {
    // Meals were logged, so there is signal to report even with no training in the window.
    const result = buildLocalFallback({ sessions: 0, mealsLogged: 3 }, 7);
    expect(result.observations.join(" ")).toMatch(/No completed workouts/i);
    expect(result.next_actions.length).toBeGreaterThan(0);
  });

  it("says nothing was recorded when every signal is zero", () => {
    // An all-zero window has no observations to report, so it must not claim there are.
    const result = buildLocalFallback({ sessions: 0, mealsLogged: 0, habitsTracked: 0 }, 7);
    expect(result.summary).toMatch(/not enough recorded data/i);
    expect(result.observations).toHaveLength(0);
  });

  it("labels the window in words", () => {
    expect(windowLabel(7)).toBe("the last 7 days");
    expect(windowLabel(30)).toBe("the last 30 days");
    expect(windowLabel(90)).toBe("the last 90 days");
  });
});

  it("rejects a whitespace-only question without calling the server", async () => {
    stubFetch(200, VALID);
    render(<CoachView fallbackInput={fallbackInput} />);
    fireEvent.change(screen.getByLabelText(/ask a question/i), { target: { value: "   " } });
    ask();

    await waitFor(() => expect(screen.getByRole("alert")).toBeTruthy());
    expect(calls).toHaveLength(0);
  });
