package com.fittrack.push;

import com.fittrack.reminder.NotificationDeliveryProvider.Outcome;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.time.Instant;
import java.util.Base64;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The VAPID / Web Push crypto path, exercised for real.
 *
 * <p>web-push 5.1.2 declares Bouncy Castle as an <em>optional</em> dependency, so Maven does not put
 * it on the classpath even though its production classes cannot run without it. Phase 13 supplies
 * {@code bcprov-jdk18on} explicitly for exactly that reason. These tests are what prove that choice
 * actually works: without them a build could compile and every delivery attempt would fail at run
 * time with a linkage error no unit test would catch.
 *
 * <p>No push service is contacted. Everything here is local key handling, so it is deterministic and
 * needs no network.
 */
class WebPushCryptoTest {

    /**
     * A real P-256 key pair, generated per test so no key material is ever hard-coded.
     *
     * <p>Returns the raw uncompressed public point (65 bytes, {@code 0x04} prefix) as well as the key
     * pair, because that - not the X.509 wrapper - is what a browser puts in {@code p256dh} and what
     * the web-push library's loader requires. Getting this wrong fails with
     * {@code Invalid point encoding type: 0x30}, where 0x30 is the ASN.1 SEQUENCE tag of the
     * wrapper, so the distinction is asserted here rather than discovered later.
     */
    private static KeyPair keyPair() throws Exception {
        registerBouncyCastleIfNeeded();
        // The library casts keys to Bouncy Castle types, so they are generated by the BC
        // provider rather than the JDK default. See verifyKeyPair in Utils.
        KeyPairGenerator generator = KeyPairGenerator.getInstance("EC", "BC");
        generator.initialize(new java.security.spec.ECGenParameterSpec("secp256r1"));
        return generator.generateKeyPair();
    }

    /** The public key as a Web Push subscription key: a raw uncompressed P-256 point. */
    private static byte[] rawPublicPoint(KeyPair pair) {
        java.security.interfaces.ECPublicKey publicKey =
                (java.security.interfaces.ECPublicKey) pair.getPublic();
        int fieldSize = (publicKey.getParams().getCurve().getField().getFieldSize() + 7) / 8;
        byte[] raw = new byte[1 + 2 * fieldSize];
        raw[0] = 0x04;
        copyLeftPadded(publicKey.getW().getAffineX().toByteArray(), raw, 1, fieldSize);
        copyLeftPadded(publicKey.getW().getAffineY().toByteArray(), raw, 1 + fieldSize, fieldSize);
        return raw;
    }

    /** The private key as web-push expects it: the 32-byte scalar, not the PKCS#8 wrapper. */
    private static byte[] rawPrivateScalar(KeyPair pair) {
        java.security.interfaces.ECPrivateKey privateKey =
                (java.security.interfaces.ECPrivateKey) pair.getPrivate();
        int fieldSize = (privateKey.getParams().getCurve().getField().getFieldSize() + 7) / 8;
        byte[] scalar = new byte[fieldSize];
        copyLeftPadded(privateKey.getS().toByteArray(), scalar, 0, fieldSize);
        return scalar;
    }

    private static void copyLeftPadded(byte[] source, byte[] target, int offset, int length) {
        int start = Math.max(0, source.length - length);
        int count = source.length - start;
        System.arraycopy(source, start, target, offset + length - count, count);
    }

    /**
     * Registers Bouncy Castle with the JCA exactly once per JVM.
     *
     * <p>web-push 5.1.2 asks for {@code KeyFactory.getInstance("EC", "BC")} and
     * {@code Signature.getInstance("SHA256withECDSA", "BC")} by provider name. Being on the classpath
     * is not enough: a JCA provider only becomes visible once it is added to
     * {@link java.security.Security}. A container that started this application without a
     * {@code java.security} entry naming BC would therefore fail every push at the first key
     * operation, which is why this registration is explicit, idempotent, and startup-visible rather
     * than left to chance.
     */
    private static synchronized void registerBouncyCastleIfNeeded() {
        if (java.security.Security.getProvider("BC") != null) return;
        try {
            java.security.Security.addProvider(
                    (java.security.Provider) Class.forName("org.bouncycastle.jce.provider.BouncyCastleProvider")
                            .getDeclaredConstructor().newInstance());
        } catch (ReflectiveOperationException | RuntimeException e) {
            throw new IllegalStateException(
                    "Bouncy Castle provider could not be registered; web push cannot work", e);
        }
    }

    private static String base64Url(byte[] value) {
        return Base64.getUrlEncoder().withoutPadding().encodeToString(value);
    }

    @Test
    @DisplayName("Phase 13 push - a VAPID key pair round-trips through the library key loader")
    void vapidKeyPairLoads() throws Exception {
        KeyPair pair = keyPair();

        assertThat(nl.martijndwars.webpush.Utils.loadPublicKey(base64Url(rawPublicPoint(pair))))
                .as("the public key the browser is given must be loadable by the server")
                .isNotNull();
        assertThat(nl.martijndwars.webpush.Utils.loadPrivateKey(base64Url(rawPrivateScalar(pair))))
                .as("the private key must load, which is what the VAPID JWT is signed with")
                .isNotNull();
    }

    @Test
    @DisplayName("Phase 13 push - a payload is encrypted for a subscriber with the selected Bouncy Castle")
    void payloadIsEncryptedForASubscriber() throws Exception {
        // A real subscriber key pair: the public key the browser would hold plus the 16-byte auth
        // secret from RFC 8291. Generating them locally means this proves the encryption path with no
        // fixture that could itself be malformed.
        KeyPair subscriber = keyPair();
        String p256dh = base64Url(rawPublicPoint(subscriber));
        String auth = base64Url(new byte[16]);
        PushSubscriptionService.validateKeys(p256dh, auth);

        var subscription = new nl.martijndwars.webpush.Subscription(
                "https://fcm.googleapis.com/fcm/send/abc123",
                new nl.martijndwars.webpush.Subscription.Keys(p256dh, auth));
        var notification = new nl.martijndwars.webpush.Notification(
                subscription, "{\"type\":\"reminder\"}", nl.martijndwars.webpush.Urgency.NORMAL);

        // preparePost is what runs the RFC 8291 content encryption, so this exercises the Bouncy
        // Castle ECDH and HKDF paths for real. No network is involved.
        var service = new nl.martijndwars.webpush.PushService();
        KeyPair vapid = keyPair();
        service.setPublicKey(vapid.getPublic());
        service.setPrivateKey(vapid.getPrivate());
        service.setSubject("mailto:ops@fittrack.example");

        var request = service.preparePost(notification, nl.martijndwars.webpush.Encoding.AES128GCM);

        assertThat(request).as("a VAPID-authenticated request is produced").isNotNull();
        // The request type is Apache HttpRequest, whose dependency is runtime-scoped, so the
        // headers are read reflectively for the same reason the provider does it.
        java.lang.reflect.Method headers = request.getClass().getMethod("getAllHeaders");
        String authorization = null;
        for (Object header : (Object[]) headers.invoke(request)) {
            if (String.valueOf(header.getClass().getMethod("getName").invoke(header)).equals("Authorization")) {
                authorization = String.valueOf(header.getClass().getMethod("getValue").invoke(header));
            }
        }
        assertThat(authorization)
                .as("the VAPID JWT is attached, identifying this application server")
                .isNotNull().startsWith("vapid");
    }

    /** Builds the notification payload through the production builder, not a copy of it. */
    private static String payloadFor(String title, String message) throws Exception {
        var method = WebPushDeliveryProvider.class.getDeclaredMethod(
                "buildPayload", com.fittrack.reminder.NotificationDeliveryProvider.DeliveryRequest.class);
        method.setAccessible(true);
        var provider = new WebPushDeliveryProvider(null, new PushProperties());
        return (String) method.invoke(provider,
                new com.fittrack.reminder.NotificationDeliveryProvider.DeliveryRequest(
                        UUID.randomUUID(), UUID.randomUUID(), title, message,
                        Instant.parse("2026-09-29T20:00:00Z")));
    }

    @Test
    @DisplayName("Phase 13 push - the payload never carries subscription secrets or user data")
    void payloadExcludesSecrets() throws Exception {
        // The payload builder is the only place notification content is assembled, so it is asserted
        // directly: a lock screen can be read by anyone nearby, so nothing sensitive travels in one.
        String payload = payloadFor("Time to train", "Session starts now");

        assertThat(payload).contains("\"type\":\"reminder\"").contains("Time to train");
        assertThat(payload)
                .doesNotContain("p256dh").doesNotContain("auth")
                .doesNotContain("token").doesNotContain("password");
    }

    @Test
    @DisplayName("Phase 13 push - a quote in a reminder title cannot break the payload")
    void payloadEscapesUserText() throws Exception {
        // A user may type a quote or a newline. Without escaping, either produces invalid JSON and the
        // browser silently drops the notification.
        String payload = payloadFor("He said \"lift\"", "line1\nline2");

        assertThat(payload).contains("\\\"").contains("\\n");
        assertThat(payload).doesNotContain("\n");
    }
}
